plugins {
    id 'com.gradleup.shadow'
}

architectury {
    platformSetupLoomIde()
    fabric()
}

loom {
    accessWidenerPath = project(":common").loom.accessWidenerPath
}


configurations {
    common
    shadowCommon // Don't use shadow from the shadow plugin because we don't want IDEA to index this.
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentFabric.extendsFrom common
}

processResources {
    filesMatching('fabric.mod.json') {
        expand rootProject.ext.replaceProperties + [project: project]
    }
}


shadowJar {
    exclude "architectury.common.json"

    configurations = [project.configurations.shadowCommon]
    archiveClassifier = "dev-shadow"
}

remapJar {
    injectAccessWidener = true
    input.set shadowJar.archiveFile
    dependsOn shadowJar
    archiveClassifier = "fabric"
}

remapSourcesJar {
    archiveClassifier = "fabric-sources"
}

jar {
    archiveClassifier = "dev"
}

sourcesJar {
    def commonSources = project(":common").sourcesJar
    dependsOn commonSources
    from commonSources.archiveFile.map { zipTree(it) }

    archiveClassifier = "fabric-sources"
}

components.java {
    withVariantsFromConfiguration(project.configurations.shadowRuntimeElements) {
        skip()
    }
}

publishing {
    publications {
        mavenFabric(MavenPublication) {
            artifactId = rootProject.mod_id + "-" + project.name
            from components.java
        }
    }
}

dependencies {
    modImplementation "net.fabricmc:fabric-loader:$fabric_loader_version"
    modApi "net.fabricmc.fabric-api:fabric-api:$fabric_api_version"

    common(project(path: ":common", configuration: "namedElements")) { transitive false }
    shadowCommon(project(path: ":common", configuration: "transformProductionFabric")) { transitive false }

    include(implementation(annotationProcessor("io.github.llamalad7:mixinextras-fabric:$mixin_extras_version")))
    annotationProcessor 'net.fabricmc:sponge-mixin:0.12.5+mixin.0.8.5'

    modCompileOnly("me.shedaniel.cloth:cloth-config-fabric:$cloth_version") {
        exclude group: 'net.fabricmc.fabric-api'
    }


    // porting_lib required by fabric & everycomp
    for (String module in port_lib_modules.split(",")) {
        modImplementation("io.github.fabricators_of_create.Porting-Lib:$module:$port_lib_version")
    }

//!! MOONLIGHT LIB (REQUIRED) --------------------------------------------------------------------------------------- \\
    //- Repository LOCAL
    String path = System.getenv('REPOS20_1')

    //- LOCAL
    if (enable_moonlight_test.toBoolean()) {
        modApi(files(path + "\\Moonlight\\fabric\\build\\libs\\moonlight-$moonlight_testVersion-fabric.jar"))
    }
    //+ MAVEN
    else {
        if (maven_backup.toBoolean()) modApi("maven.modrinth:moonlight:$moonlight_version-fabric")
        else modApi("net.mehvahdjukaar:moonlight-fabric:$moonlight_version:fabric") { transitive = false }
    }


//!! Supplementaries ================================================================================================ \\

    //- ~/fabric/mods LOCAL
//     modImplementation("net.mehvahdjukaar:supplementaries-fabric:${project.supplementaries_version}")

//!! TOOLS ========================================================================================================== \\
    modRuntimeOnly("dev.emi:emi-fabric:$emi_version+$minecraft_version")
    modRuntimeOnly("com.blamejared.crafttweaker:CraftTweaker-fabric-$minecraft_version:$crafttweaker_version")
    modRuntimeOnly("mezz.jei:jei-$minecraft_version-fabric:$jei_version")
//    modRuntimeOnly("curse.maven:jade-324717:5666690")

//!! ================================================ DEPENDENCIES ================================================== \\
    //- ONLY FOR TESTING - can be commented out or enabled
    modRuntimeOnly("com.github.glitchfiend:TerraBlender-fabric:$minecraft_version-$terrablender_version") // Biomes-O'-Plenty, Regions-Unexplored
    modRuntimeOnly("com.github.glitchfiend:GlitchCore-fabric:$minecraft_version-$glitchcore_version") // Biomes-O'-Plenty

//    modRuntimeOnly("curse.maven:ctm-267602:5983309") // Chipped
//    modRuntimeOnly("curse.maven:cloth-config-348521:4973440") // v11.1.118 | REI
//    modRuntimeOnly("curse.maven:architectury-api-419699:5137936") // v9.2.14 | REI, Garden-Of-The-Dead
//    modRuntimeOnly("curse.maven:trinkets-341284:5173501") // Backpacked
//    modRuntimeOnly("curse.maven:athena-841890:5176880") // Chipped
//    modRuntimeOnly("curse.maven:resourceful-lib-570073:5659872") //v2.1.29 | Chipped, Handcrafted, Cozy
//    modRuntimeOnly("curse.maven:owo-lib-532610:4749199") //v0.11.2 | Infinity-Buttons

            //- OTHER MAVENS
//    modRuntimeOnly("com.terraformersmc.terraform-api:terraform-wood-api-v1:7.0.3") // Blockus
//    modRuntimeOnly("com.terraformersmc.terraform-api:terraform-shapes-api-v1:7.0.3") // Blockus
//    modRuntimeOnly("com.terraformersmc:biolith:1.0.0-alpha.8") // Blockus
//    modRuntimeOnly("fuzs.forgeconfigapiport:forgeconfigapiport-fabric:8.0.2") // Regions-Unexplored, Chipped, Excessive-Building, Create
//    modRuntimeOnly("dev.engine-room.flywheel:flywheel-fabric-$minecraft_version:$flywheel_fabric_version") // Create
//    modRuntimeOnly("net.createmod.ponder:Ponder-Fabric-$minecraft_version:$ponder_fabric_version") // Create
//    modRuntimeOnly("io.github.tropheusj:milk-lib:1.3.61") // Create

    //+ REQUIRED - The modules access libraries from below - ONLY IN fABRIC
    modCompileOnly("curse.maven:framework-549225:7573737") // v0.8 | Refurbished Furniture, Mighty Mail, Backpacked
    modCompileOnly("curse.maven:quad-932715:5146132") // More Crafting Tables
    modCompileOnly("maven.modrinth:frozenlib:1.9.3-mc1.20.1") // Wilder-Wild
    modCompileOnly("curse.maven:valhelsia-core-416935:5376599") // Valhelsia-Furniture

        //+ OTHER MAVENS
    modCompileOnly("com.tterrag.registrate_fabric:Registrate:$registrate_fabric_version") // Create

            // Special dumb stuff required by TerraBlender
    modImplementation("com.terraformersmc:modmenu:7.2.2")
    modImplementation("dev.onyxstudios.cardinal-components-api:cardinal-components-base:5.2.2")
    modImplementation("dev.onyxstudios.cardinal-components-api:cardinal-components-entity:5.2.2")
            // so dumber stuff requird by GlitchCore
    modRuntimeOnly("net.jodah:typetools:0.6.3") // Biomes-O'-Plenty

    // IMPORTANT: RLM: "REQUIRED LOCAL MOD" - You need to get the mod and put it in ~/fabric/run/mods/....
//!! ================================================== IMPORTS ===================================================== \\
    //- ONLY FOR TESTING - can be commented out or enabled
//    modRuntimeOnly("curse.maven:another-furniture-610492:4815126") //
//    modRuntimeOnly("curse.maven:backpacked-352835:7624223") // Framework
//    modRuntimeOnly("curse.maven:blockus-312289:6256096") // Terraformermc-[Wood-APi, Shapes-API, Biolith]
//    modRuntimeOnly("curse.maven:building-but-better-989479:5362379") // has a built-in module
//    modRuntimeOnly("curse.maven:camp-chair-531744:4579676")
//    modRuntimeOnly("curse.maven:chipped-456956:4634858") // v3.0.1 | Athena, Resourceful-Lib, Forge-Config-Api-Port
//    modRuntimeOnly("curse.maven:dawn-of-time-312359:6863594") // Fusion, YetAnotherConfigLib
//    modRuntimeOnly("curse.maven:decorative-blocks-362528:5089408")
//    modRuntimeOnly("curse.maven:exlines-bark-carpets-527296:4062547")
//    modRuntimeOnly("curse.maven:farmers-delight-refabricated-993166:6626608")
//    modRuntimeOnly("curse.maven:friends-and-foes-551364:6354623")
//    modRuntimeOnly("curse.maven:hearth-and-home-849364:4828281")
//    modRuntimeOnly("curse.maven:handcrafted-538214:5118730")
//    modRuntimeOnly("curse.maven:furnish-547069:4821516")
//    modRuntimeOnly("curse.maven:more-chest-variants-lieonlion-858032:5476602") // Quad - LieOnLion
//    modRuntimeOnly("curse.maven:more-crafting-tables-lieonlion-913586:5330969") // Quad - LieOnLion
//    modRuntimeOnly("curse.maven:missing-wilds-622590:5053651")
//    modRuntimeOnly("curse.maven:refurbished-furniture-897116:6272883") // Framework
//    modRuntimeOnly("curse.maven:villagersplus-fabric-809542:4996993")
//    modRuntimeOnly("curse.maven:storage-drawers-223852:6994478")
//    modRuntimeOnly("curse.maven:table-top-craft-fabric-729535:5319819") //RLM: exp4j
//    modRuntimeOnly("curse.maven:twigs-496913:4603805")
//    modRuntimeOnly("curse.maven:valhelsia-furniture-694349:5189603")
//    modRuntimeOnly("curse.maven:variant-vanilla-blocks-866509:5150741") //v1.3.8

        //- OTHER MAVENS
//    modRuntimeOnly("maven.modrinth:stylish-stiles:zLlRqz68")
//    modRuntimeOnly("earth.terrarium.chipped:chipped-fabric-$minecraft_version:3.0.7") //INCLUDED: Athena, Resourceful-Lib, REQUIRED: Forge-Config-Api-Port, ConnectedTexturesMod (CTM)

        //- ~/fabric/mods LOCAL
//    modRuntimeOnly("com.arcanc.bc:beautifulcampfires-fabric-1.20.1-1.0.0")

    //+ REQUIRED - The modules access libaries from below - ONLY IN FABRIC
        // ~/fabric/mods LOCAL
    modCompileOnly("net.stehschnitzel.shutter:shutter-2.0.2-1.20.1")
    modCompileOnly("net.darktree.redbits:redbits-1.20.1-1.16.1")

        // MACAW's
    modCompileOnly("curse.maven:macaws-bridges-351725:5240495")
    modCompileOnly("curse.maven:macaws-doors-378646:7618793")
    modCompileOnly("curse.maven:macaws-fences-and-walls-453925:7308361")
    modCompileOnly("curse.maven:macaws-lights-and-lamps-502372:5450302")
    modCompileOnly("curse.maven:macaws-paths-and-pavings-629153:8207352")
    modCompileOnly("curse.maven:macaws-roofs-352039:4590013")
    modCompileOnly("curse.maven:macaws-trapdoors-400933:5977711")
    modCompileOnly("curse.maven:macaws-windows-363569:4750644")
    modCompileOnly("curse.maven:macaws-furniture-359540:7197865")
    modCompileOnly("curse.maven:macaws-stairs-1119394:6155218")

        // GENERAL
    modCompileOnly("curse.maven:architects-palette-fabric-487364:3845046") //!! NOT AVAILABLE
    modCompileOnly("curse.maven:beautify-refabricated-809311:5405529")
    modCompileOnly("curse.maven:bewitchment-394915:5205373")
    modCompileOnly("curse.maven:building-but-better-989479:6803573")
    modCompileOnly("curse.maven:clutter-826060:5828924") //RML: Geckolib
    modCompileOnly("curse.maven:dramatic-doors-380617:6438745")
    modCompileOnly("curse.maven:excessive-building-845097:6051029") // Forge-Config-Api-Port
    modCompileOnly("curse.maven:exlines-awnings-526698:4668406")
    modCompileOnly("curse.maven:farmers-delight-fabric-482834:4939709") // legacy
    modCompileOnly("curse.maven:infinity-buttons-661902:5409967") // Owo-Lib
    modCompileOnly("curse.maven:lightmans-currency-fabric-724119:5544643")
    modCompileOnly("curse.maven:mighty-mail-fabric-904097:4750271")
    modCompileOnly("curse.maven:regions-unexplored-659110:5558172") // Forge-Config-Api-Port
    modCompileOnly("curse.maven:storage-delight-fabric-978786:6696778")
    modCompileOnly("curse.maven:the-twilight-forest-227639:4389094") //!! NOT AVAILABLE
    modCompileOnly("curse.maven:wooden-hoppers-406021:4796143")

        // OTHER MAVENS
    modCompileOnly("maven.modrinth:wilder-wild:3.0.7-mc1.20.1") // FrozenLib
    modCompileOnly("com.simibubi.create:create-fabric:$create_fabric_version") { transitive = false }  // Registrate, Flywheel, Ponder, Forge-Config-Api-Port, Milk-Lib

    // ======================================== DISABLED FOR A REASON =============================================== \\

//    modCompileOnly("curse.maven:cozy-625281:4728202")

//!! ============================================== FOR TESTING ===================================================== \\

//    modRuntimeOnly("curse.maven:gardens-of-the-dead-683174:4784268")
    modRuntimeOnly("curse.maven:biomes-o-plenty-220318:6028853")
//    modRuntimeOnly("curse.maven:natures-spirit-1044992:6962787")

}
