plugins {
    id "architectury-plugin" version "3.4-SNAPSHOT" apply false
    id "dev.architectury.loom" version "1.13.+" apply false
    id "io.github.juuxel.loom-quiltflower" version "1.7.1" apply false
    id "com.matthewprenger.cursegradle" version "1.+"
    id "com.modrinth.minotaur" version "2.+"
    id "com.possible-triangle.publishing" version "1.2.67" apply false
}

allprojects {
    apply plugin: "java"
    apply plugin: "architectury-plugin"
    apply plugin: "com.possible-triangle.publishing"

    group = mod_group_id
    version = mod_version
    archivesBaseName = mod_id

    repositories {
        // Standard repositories
        mavenLocal()
        mavenCentral()

        // Flat directory for local mods
        flatDir { dirs "mods" }

        // Our publishing repo
        if (!maven_backup.toBoolean()) maven { url = "https://registry.somethingcatchy.net/repository/maven-releases/" }

        maven { url = "https://api.modrinth.com/maven" }
        maven { url = "https://www.cursemaven.com" }
        maven { url = "https://jitpack.io" }

        maven { url = "https://maven.neoforged.net" }
        maven { url = "https://maven.architectury.dev" }
        maven { url = "https://maven.parchmentmc.org" }

        maven { url = "https://maven.createmod.net" } // Create Mod, Ponder, Flywheel
        maven { url = "https://maven.blamejared.com" } // JEI, Vazkii's Mods
        maven { url = "https://maven.ladysnake.org/releases" } // Ladysnake mods
        maven { url = "https://maven.tterrag.com/" } // Flywheel, EnderIO
        maven { url = "https://maven.ithundxr.dev/snapshots" } // Registrate
        maven { url = "https://mvn.devos.one/releases/" } // Registrate, Porting Lib (releases)
        maven { url = "https://mvn.devos.one/snapshots/" } // Registrate, Porting Lib (snapshots)
        maven { url = "https://maven.terraformersmc.com/" } // EMI
        maven { url = "https://maven.saps.dev/releases" } // FTB Mods

        maven { url = "https://maven.theillusivec4.top/" } // Curios API
        maven { url = "https://maven.squiddev.cc" } // CC: Tweaked
        maven { url = "https://maven.su5ed.dev/releases" } // SU5ED mods
        maven { url = "https://harleyoconnor.com/maven" } // Dynamic Trees
        maven { url = "https://maven.misterpemodder.com/libs-release/" } // ShulkerBoxTooltip
        maven { url = "https://maven.firstdarkdev.xyz/snapshots" } // FirstDarkDev (snapshots)
        maven { url = "https://raw.githubusercontent.com/Fuzss/modresources/main/maven" } // NeoForge-config-API-port

        maven { url = "https://mvn.devos.one/snapshots/" }
        maven { url = "https://mvn.devos.one/releases" } // Porting Lib Releases
        maven { url = "https://maven.shedaniel.me/" } // Cloth Config
        maven { url = "https://maven.createmod.net" } // Create, Ponder, Flywheel
        maven { url = "https://raw.githubusercontent.com/Fuzss/modresources/main/maven" } // Forge-Config-API-Port
        maven { url = "https://squiddev.cc/maven" } // CC: Tweaked
        maven { name = "Jared's maven"; url = "https://maven.blamejared.com/" } // JEI, CraftTweaker
        maven { name = "ModMaven"; url = "https://modmaven.dev" } // Botania & FALLBACK for JEI
        maven { url = "https://maven.teamresourceful.com/repository/maven-public/" } // Chipped
        maven { url = "https://maven.firstdarkdev.xyz/snapshots" }
        maven { name = "TerraformersMC"; url = "https://maven.terraformersmc.com/" }
        maven { url = "https://raw.githubusercontent.com/moddingplayground/maven/main/" }
        maven { name = "Xander Maven"; url = "https://maven.isxander.dev/releases" } // Yet-Another-Config-Lib
        maven { url = "https://maven.resourcefulbees.com/repository/maven-public/" } // Resourceful-Lib

        maven { // Reach Entity Attributes
            url = "https://maven.jamieswhiteshirt.com/libs-release"
            content { includeGroup("com.jamieswhiteshirt") }
        }

    }
    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(rootProject.java_version.toInteger())
        }
        withSourcesJar()
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = "UTF-8"
    }
}

architectury {
    minecraft = minecraft_version
}

subprojects {
    apply plugin: "dev.architectury.loom"
    apply plugin: "com.matthewprenger.cursegradle"
    apply plugin: "com.modrinth.minotaur"

    loom {
        silentMojangMappingsLicense()
    }

    dependencies {
        minecraft "com.minecraft:minecraft:${rootProject.minecraft_version}"
        mappings loom.layered() {
            it.officialMojangMappings {
                setNameSyntheticMembers(false)
            }
            it.parchment("org.parchmentmc.data:parchment-${rootProject.parchment_version}")
        }

    }

    publishing {
        repositories {
            mavenLocal()

            def nexusToken = providers.environmentVariable("NEXUS_TOKEN").get()
            def nexusUser = providers.environmentVariable("NEXUS_USER").get()
            if (nexusToken && nexusUser) {
                maven {
                    url = uri("https://registry.somethingcatchy.net/repository/maven-releases/")
                    credentials {
                        username = nexusUser
                        password = nexusToken
                    }
                }
            }
        }
    }

    var env = System.getenv()
    var modLoader = name

    var changelogFile = rootProject.file("changelog.md")
    var changelogText = changelogFile.exists() ? changelogFile.text : ""

    var versions = listGameVersions(minecraft_min_version, minecraft_version)

    if (env.MODRINTH_TOKEN) {
        modrinth {
            projectId = modrinth_id
            uploadFile = tasks.remapJar
            additionalFiles.add(tasks.remapSourcesJar)
            gameVersions = versions
            if (modLoader == "forge") {
                loaders = ["neoforge"]
            } else loaders = [modLoader]

            changelog = changelogText
            versionNumber = mod_version +"-"+ modLoader
            versionType = release_type

            if (modLoader == "fabric") {
                dependencies {
                    required.project "fabric-api"
                    required.project "moonlight"
                    optional.project("another-furniture")
                    optional.project("architects-palette-fabric")
//                    optional.project("backpacked")
                    optional.project("guitas-woodworks")
                    optional.project("building-but-better")
                    optional.project("camp-chair")
                    optional.project("chipped")
                    optional.project("clutter")
//                    optional.project("corail-pillar")
                    optional.project("create-fabric")
                    optional.project("dawn-of-time")
                    optional.project("decorative-blocks")
                    optional.project("dramatic-doors")
                    optional.project("exlines-awnings")
                    optional.project("bark-carpets")
                    optional.project("excessive-building")
                    optional.project("farmers-delight-fabric")
                    optional.project("farmers-delight-refabricated")
                    optional.project("friends-and-foes")
                    optional.project("furnish")
                    optional.project("handcrafted")
                    optional.project("hearth-and-home")
                    optional.project("infinitybuttons")
                    optional.project("lightmans-currency")
                    optional.project("macaws-bridges")
                    optional.project("macaws-doors")
                    optional.project("macaws-fences-and-walls")
                    optional.project("macaws-furniture")
                    optional.project("macaws-lights-and-lamps")
                    optional.project("macaws-paths-and-pavings")
                    optional.project("macaws-roofs")
                    optional.project("macaws-trapdoors")
                    optional.project("macaws-windows")
//                    optional.project("mighty-mail-fabric")
                    optional.project("missing-wilds")
                    optional.project("more-beautiful-torches")
                    optional.project("more-crafting-tables-lieonlion")
                    optional.project("quark")
                    optional.project("regions-unexplored")
//                    optional.project("the-twilight-forest") //NOT AVAILABLE
                    optional.project("table-top-craft")
                    optional.project("twigs")
                    optional.project("valhelsia-furniture")
                    optional.project("variant-vanilla-blocks")
                    optional.project("villagersplus")
                    optional.project("wooden-hoppers")
                }
            } else {
                dependencies {
                    required.project "moonlight"
                    optional.project("sawmill")
                    optional.project("absent-by-design")
                    optional.project("another-furniture")
                    optional.project("architects-palette")
                    optional.project("bibliocraft-legacy")
                    optional.project("boatload")
                    optional.project("guitas-woodworks")
                    optional.project("buildersaddition")
                    optional.project("building-but-better")
                    optional.project("camp-chair")
                    optional.project("chipped")
//                    optional.project("corail-pillar")
                    optional.project("create")
                    optional.project("decorative-blocks")
//                    optional.project("decoration-delight")
//                    optional.project("domum-ornamentum")
                    optional.project("dramatic-doors")
                    optional.project("bark-carpets")
                    optional.project("excessive-building")
                    optional.project("farmers-delight")
                    optional.project("friends-and-foes-forge")
                    optional.project("functional-storage")
                    optional.project("furnish")
                    optional.project("handcrafted")
                    optional.project("hearth-and-home")
                    optional.project("infinitybuttons")
                    optional.project("just-a-raft-mod")
                    optional.project("lightmans-currency")
                    optional.project("macaws-bridges")
                    optional.project("macaws-doors")
                    optional.project("macaws-fences-and-walls")
                    optional.project("macaws-furniture")
                    optional.project("macaws-lights-and-lamps")
                    optional.project("macaws-paths-and-pavings")
                    optional.project("macaws-roofs")
                    optional.project("macaws-trapdoors")
                    optional.project("macaws-windows")
//                    optional.project("mighty-mail")
                    optional.project("missing-wilds")
                    optional.project("more-beautiful-torches")
                    optional.project("more-chest-variants-lieonlion")
//                    optional.project("more-crafting-tables-for-forge")
                    optional.project("more-crafting-tables-lieonlion")
                    optional.project("mosaic-carpentry")
//                    optional.project("pokecube-aoi")
                    optional.project("premium-wood")
//                    optional.project("productivebees")
                    optional.project("quark")
                    optional.project("redeco")
                    optional.project("regions-unexplored")
                    optional.project("storage-drawers")
                    optional.project("timber-frames")
                    optional.project("the-graveyard-forge")
                    optional.project("the-twilight-forest")
                    optional.project("table-top-craft")
                    optional.project("tropicraft")
                    optional.project("twigs")
                    optional.project("valhelsia-furniture")
                    optional.project("variant-crafting-tables")
                    optional.project("variant-vanilla-blocks")
                    optional.project("villagersplus")
                    optional.project("woodworks")
                    optional.project("workshop-for-handsome-adventurer")
                    optional.project("xercamod")
                }
            }
        }
    }

    if (env.CURSEFORGE_TOKEN) {
        curseforge {
            apiKey = env.CURSEFORGE_TOKEN
            project {
                id = curseforge_id
                changelog = changelogText
                changelogType = 'markdown'
                releaseType = release_type
                for (var ver : versions) {
                    addGameVersion ver
                }
                if (modLoader == "neoforge") {
                    addGameVersion("NeoForge")
                } else addGameVersion modLoader.capitalize()

                mainArtifact(tasks.remapJar)

                if (modLoader == "fabric") {
                    relations {
                        requiredDependency "fabric-api"
                        requiredDependency "selene"
                        optionalDependency("another-furniture")
                        optionalDependency("architects-palette-fabric")
                        optionalDependency("backpacked")
                        optionalDependency("guitas-woodworks")
                        optionalDependency("building-but-better")
                        optionalDependency("camp-chair")
                        optionalDependency("chipped")
                        optionalDependency("clutter")
                        optionalDependency("create-fabric")
                        optionalDependency("decorative-blocks")
                        optionalDependency("dramatic-doors")
                        optionalDependency("exlines-awnings")
                        optionalDependency("exlines-bark-carpets")
                        optionalDependency("excessive-building")
                        optionalDependency("farmers-delight-fabric")
                        optionalDependency("farmers-delight-refabricated")
                        optionalDependency("friends-and-foes")
                        optionalDependency("furnish")
                        optionalDependency("handcrafted")
                        optionalDependency("hearth-and-home")
                        optionalDependency("infinitybuttons")
                        optionalDependency("lightmans-currency-fabric")
                        optionalDependency("macaws-bridges")
                        optionalDependency("macaws-doors")
                        optionalDependency("macaws-fences-and-walls")
                        optionalDependency("macaws-furniture")
                        optionalDependency("macaws-lights-and-lamps")
                        optionalDependency("macaws-paths-and-pavings")
                        optionalDependency("macaws-roofs")
                        optionalDependency("macaws-trapdoors")
                        optionalDependency("macaws-windows")
                        optionalDependency("mighty-mail-fabric")
                        optionalDependency("missing-wilds")
                        optionalDependency("more-beautiful-torches")
                        optionalDependency("more-crafting-tables-lieonlion")
                        optionalDependency("quark")
                        optionalDependency("refurbished-furniture")
                        optionalDependency("regions-unexplored")
//                        optionalDependency("the-twilight-forest") //NOT AVAILABLE
                        optionalDependency("table-top-craft-fabric")
                        optionalDependency("twigs")
                        optionalDependency("valhelsia-furniture")
                        optionalDependency("variant-vanilla-blocks")
                        optionalDependency("villagersplus-fabric")
                        optionalDependency("wooden-hoppers")
                    }
                } else {
                    relations {
                        requiredDependency("selene")
                        optionalDependency("sawmill")
                        optionalDependency("absent-by-design")
                        optionalDependency("another-furniture")
                        optionalDependency("architects-palette")
                        optionalDependency("backpacked")
                        optionalDependency("bibliocraft-legacy")
                        optionalDependency("boatload")
                        optionalDependency("guitas-woodworks")
                        optionalDependency("buildersaddition")
                        optionalDependency("building-but-better")
                        optionalDependency("camp-chair")
                        optionalDependency("chipped")
                        optionalDependency("corail-pillar")
                        optionalDependency("create")
                        optionalDependency("dawn-of-time")
                        optionalDependency("decorative-blocks")
                        optionalDependency("decoration-delight")
                        optionalDependency("domum-ornamentum")
                        optionalDependency("dramatic-doors")
                        optionalDependency("exlines-bark-carpets")
                        optionalDependency("excessive-building")
                        optionalDependency("farmers-delight")
                        optionalDependency("friends-and-foes-forge")
                        optionalDependency("functional-storage")
                        optionalDependency("furnish")
                        optionalDependency("handcrafted")
                        optionalDependency("hearth-and-home")
                        optionalDependency("infinitybuttons")
                        optionalDependency("just-a-raft-mod")
                        optionalDependency("lightmans-currency")
                        optionalDependency("macaws-bridges")
                        optionalDependency("macaws-doors")
                        optionalDependency("macaws-fences-and-walls")
                        optionalDependency("macaws-furniture")
                        optionalDependency("macaws-lights-and-lamps")
                        optionalDependency("macaws-paths-and-pavings")
                        optionalDependency("macaws-roofs")
                        optionalDependency("macaws-trapdoors")
                        optionalDependency("macaws-windows")
                        optionalDependency("mighty-mail")
                        optionalDependency("missing-wilds-forge")
                        optionalDependency("more-beautiful-torches")
                        optionalDependency("more-chest-variants-lieonlion")
                        optionalDependency("more-crafting-tables-for-forge")
                        optionalDependency("more-crafting-tables-lieonlion")
                        optionalDependency("mosaic-carpentry")
                        optionalDependency("pokecube-aoi")
                        optionalDependency("premium-wood")
//                        optionalDependency("productivebees")
                        optionalDependency("quark")
                        optionalDependency("redeco")
                        optionalDependency("refurbished-furniture")
                        optionalDependency("regions-unexplored")
                        optionalDependency("storage-drawers")
                        optionalDependency("timber-frames")
                        optionalDependency("the-graveyard-forge")
                        optionalDependency("the-twilight-forest")
                        optionalDependency("table-top-craft")
                        optionalDependency("tropicraft")
                        optionalDependency("twigs")
                        optionalDependency("valhelsia-furniture")
                        optionalDependency("variant-crafting-tables")
                        optionalDependency("variant-vanilla-blocks")
                        optionalDependency("villagersplus-forge")
                        optionalDependency("woodworks")
                        optionalDependency("workshop-for-handsome-adventurer")
                        optionalDependency("xercamod")
                    }
                }
            }
        }
    }

}

// --- Utils
static def listGameVersions(String minVersion, String maxVersion) {
// minVersion like "1.20", maxVersion like "1.20.4"
    def versions = []
    versions << minVersion
    int endPatch = Integer.parseInt(maxVersion.split('\\.')[2])
    for (int i = 1; i <= endPatch; i++) {
        versions << "${minVersion}.${i}"
    }
    return versions
}

ext {
    usesMavenLocalML = System.getenv().MY_PC == "1"
    print "isMyPc: $usesMavenLocalML"
    replaceProperties = [
            minecraft_version    : minecraft_version,
            minecraft_min_version: minecraft_min_version,
            minecraft_max_version: minecraft_max_version,
            pack_format_number   : pack_format_number,

            mod_id               : mod_id,
            mod_name             : mod_name,
            mod_version          : mod_version,
            mod_license          : mod_license,
            mod_authors          : mod_authors,
            mod_description      : mod_description,
            mod_credits          : mod_credits,
            mod_homepage         : mod_homepage,
            mod_github           : mod_github,

            neo_version          : neo_version,
            neo_version_range    : neo_version_range,
            loader_version_range : loader_version_range,

            moonlight_required_version: moonlight_required_version
    ]
}


tasks.register('buildAndPublishAll') {
    group 'build'
    description 'Runs clean, build, and publish neoforge and fabric'

    dependsOn ';clean'
    dependsOn ';build'
    dependsOn ':neoforge:curseforge'
    dependsOn ':neoforge:modrinth'
    dependsOn ':fabric:curseforge'
    dependsOn ':fabric:modrinth'
    dependsOn ':publish'
}

tasks.register('cleanLogs', Delete) {
    group "build"
    description "Delete logs"

    // Logs
    delete fileTree(dir: "$rootDir/neoforge/run/logs", include: "**/*.gz")
    delete fileTree(dir: "$rootDir/fabric/run/logs", include: "**/*.gz")
}

tasks.register('cleanFolders', Delete) {
    group "build"
    description "Clean logs & Delete folders of Debug, Dynamic Pack"

    // Logs
    delete fileTree(dir: "$rootDir/neoforge/run/logs", include: "**/*.gz")
    delete fileTree(dir: "$rootDir/fabric/run/logs", include: "**/*.gz")

    // Debug
    delete "$rootDir/neoforge/run/debug"
    delete "$rootDir/fabric/run/debug"

    // Dynamic Data Pack Cache
    delete "$rootDir/neoforge/run/dynamic-data-pack-cache"
    delete "$rootDir/fabric/run/dynamic-data-pack-cache"

    // Dynamic Resource Pack Cache
    delete "$rootDir/neoforge/run/dynamic-resource-pack-cache"
    delete "$rootDir/fabric/run/dynamic-resource-pack-cache"
}
