loom.ignoreDependencyLoomVersionValidation = true
loom.allowMismatchedPlatformVersions = true
fabric.loom.multiProjectOptimisation = false

org.gradle.jvmargs = -Xmx7048M
org.gradle.warning.mode = none
#org.gradle.logging.level= quiet

#!! Publication Info
mod_id = everycomp
maven_group = net.mehvahdjukaar
curseforge_id = 1310308
modrinth_id = library-section
    #!! VERSION
mod_version = 1.20-2.8.13

# MINECRAFT
minecraft_version = 1.20.1
enabled_platforms = fabric,forge

# FORGE
forge_version = 1.20.1-47.4.0

# FABRIC
fabric_loader_version = 0.16.10
fabric_api_version = 0.92.3+1.20.1

#!! LIBRARY | DEPENDENCIES
    # COMMON
moonlight_mavenVersion = 1.20-2.14.13
        #@ TESTING PURPOSE
moonlight_testVersion = 1.20-2.14.13
enable_moonlight_test = false

        # OTHER
mixin_extras_version = 0.4.0
architectury_version = 5.7.28
terrablender_version = 3.0.1.10
glitchcore_version = 0.0.1.0

# Get the version from https://www.curseforge.com/minecraft/mc-mods/emi/files/all?page=1&pageSize=20&version=1.20.1
emi_version = 1.1.22
# Get the version from https://github.com/CraftTweaker/CraftTweaker/tree/1.20.1
crafttweaker_version = 14.0.57
# Get the version from https://parchmentmc.org/docs/getting-started
parchment_version = 1.20.1:2023.09.03

    # FABRIC
# Get the correct version @ https://modrinth.com/mod/modmenu/versions
modmenu_version = 4.0.0
cloth_version = 11.0.99
port_lib_version= 2.3.8+1.20.1
port_lib_modules = accessors,attributes,base,common,entity,extensions,lazy_registration,model_generators,model_loader,models,networking,obj_loader,tags,transfer

# Get the correct version @ https://modrinth.com/mod/create-fabric/versions
#create_fabric_version = 0.5.1-j-build.1631+mc1.20.1
#flywheel_fabric_version = 1.20.1-0.6.11-13
#registrate_fabric_version = 1.3.62-MC1.20.1

    # FORGE
# Get the correct version @ https://maven.createmod.net/com/simibubi/create/
#create_version = 6.0.2-52
# Get the correct version @ https://maven.createmod.net/dev/engine-room/flywheel/
#flywheel_version = 1.0.1
# Get the correct version @ https://maven.createmod.net/net/createmod/ponder/
#ponder_version = 1.0.51
# Get the correct version @ https://maven.tterrag.com/com/tterrag/registrate/Registrate/
#registrate_version = MC1.20-1.3.3
