org.gradle.jvmargs = -Xmx7048M
org.gradle.warning.mode = none
org.gradle.logging.level= quiet
org.gradle.parallel = true
org.gradle.daemon = false
fabric.loom.ignoreDependencyLoomVersionValidation = true
fabric.loom.allowMismatchedPlatformVersions = true
fabric.loom.multiProjectOptimisation = false

# MINECRAFT
mc_version = 1.21.1
minecraft_version = 1.21.1

#!! Publication Info
mod_id = everycomp
mod_name = Every Compat
release_type = release
curseforge_project_id = 628539
modrinth_project_id = every-compat

maven_group = net.mehvahdjukaar
mod_group_id = net.mehvahdjukaar
repository = MehVahdJukaar/WoodGood
mod_authors = MehVahdJukaar, Xel'Bayria, WenXin2
mod_description = Ultimate Wood Compat Mod
mod_homepage = https://www.curseforge.com/minecraft/mc-mods/every-compat
mod_github = https://github.com/MehVahdJukaar/WoodGood
mod_credits = Plantkillable, Frogbirdd, Pau_1eal
mod_license = Supplementaries Team License v.1.1

    #!! VERSION
mod_version = 1.21-2.11.41

#!! LOADERS
parchment_mappings_version = 2024.11.17
    # FABRIC
fabric_loader_version = 0.19.2
fabric_api_version = 0.116.12+1.21.1

    # NEOFORGE
neoforge_version = 21.1.233


#!! LIBRARY | DEPENDENCIES

# an alternative maven, just in case if somethingcatchy maven is down
maven_backup = false

    #!! COMMON
# Required Version
moonlight_required_version = 1.21-2.29.0

# Get the version @ https://registry.somethingcatchy.net/#browse/search/generic=keyword%3Dmoonlight
moonlight_version = 1.21-2.29.30
    #@ TESTING PURPOSE
moonlight_testVersion = 1.21-2.29.19
enable_moonlight_test = false

emi_version = 1.1.22
crafttweaker_version = 21.0.35
yacl_version = 3.8.1+1.21.1
resourcefullib_version = 3.0.12

architectury_version=5.7.28

    #!! FABRIC
port_lib_version= 2.3.4+1.20.1
port_lib_modules = accessors,attributes,base,brewing,common,entity,extensions,lazy_registration,model_generators,model_loader,models,networking,obj_loader,tags,transfer
modmenu_version = 4.0.0
cloth_version = 11.0.99

create_fabric_version = 0.5.1-j-build.1634+mc1.20.1
flywheel_fabric_version = 1.20.1-0.6.11-13
ponder_fabric_version = 1.0.92
registrate_fabric_version = 1.3.62-MC1.20.1

    #!! NEOFORGE
create_version = 6.0.8-169
flywheel_version = 1.0.5-32
ponder_version = 1.0.69
registrate_version = MC1.21-1.3.0+62
