loom.ignoreDependencyLoomVersionValidation = true
loom.allowMismatchedPlatformVersions = true
fabric.loom.multiProjectOptimisation = false

org.gradle.jvmargs = -Xmx7048M
org.gradle.warning.mode = none
org.gradle.logging.level= quiet

# MINECRAFT
minecraft_version = 1.20.1
minecraft_min_version = 1.20
minecraft_max_version = 1.21

pack_format_number = 15
enabled_platforms = fabric,forge

#!! Publication Info
mod_id = everycomp
mod_name = Every Compat
release_type = release
curseforge_id = 628539
modrinth_id = every-compat

mod_group_id = net.mehvahdjukaar
mod_authors = MehVahdJukaar, Xel'Bayria, WenXin2
mod_description = Ultimate Wood Compat Mod
mod_homepage = https://www.curseforge.com/minecraft/mc-mods/every-compat
mod_github = https://github.com/MehVahdJukaar/WoodGood
mod_credits = Plantkillable, Frogbirdd, Pau_1eal
mod_license = Supplementaries Team License v.1.1

    #!! VERSION
mod_version = 1.20-2.9.24

#!! LOADERS

#      ┌──────────────────────────────────────────────────────────┐
#      │                          COMMON                          │
#      └──────────────────────────────────────────────────────────┘

# ─────────────────────────────────── MOONLIGHT-LIB ────────────────────────────────────
# an alternative maven, just in case if somethingcatchy maven is down
maven_backup = false

# Required Version
moonlight_required_version = 1.20-2.16.35

# Get the version @ https://registry.somethingcatchy.net/#browse/search/generic=keyword%3Dmoonlight
moonlight_version = 1.20-2.16.35
        #@ TESTING PURPOSE
moonlight_testVersion = 1.20-2.16.35
enable_moonlight_test = false

# ──────────────────────────────────── DEPENDENCIES ────────────────────────────────────
mixin_extras_version = 0.4.1
architectury_version = 5.7.28
terrablender_version = 3.0.1.10
glitchcore_version = 0.0.1.0

# Get the version @ https://www.curseforge.com/minecraft/mc-mods/emi/files/all?page=1&pageSize=20&version=1.20.1
emi_version = 1.1.24
# Get the version @ https://www.curseforge.com/minecraft/mc-mods/jei/files/all?page=1&pageSize=20&version=1.20.1
jei_version = 15.20.0.132
# Get the version @ https://github.com/CraftTweaker/CraftTweaker/tree/1.20.1
crafttweaker_version = 14.0.57
# Get the version @ https://parchmentmc.org/docs/getting-started
parchment_version = 1.20.1:2023.09.03

#      ┌──────────────────────────────────────────────────────────┐
#      │                          FABRIC                          │
#      └──────────────────────────────────────────────────────────┘
fabric_loader_version = 0.17.3
fabric_api_version = 0.92.6+1.20.1

# ──────────────────────────────────── DEPENDENCIES ────────────────────────────────────
# Get the correct version @ https://modrinth.com/mod/modmenu/versions
modmenu_version = 4.0.0
cloth_version = 11.0.99
# Get the correct version @ https://mvn.devos.one/#/releases/io/github/fabricators_of_create/Porting-Lib
port_lib_version= 2.3.14+1.20.1
port_lib_modules = accessors,base,brewing,client_events,entity,extensions,networking,obj_loader,transfer,models

# Get the correct version @ https://mvn.devos.one/#/snapshots/com/simibubi/create/create-fabric-1.20.1
create_fabric_version = 6.0.8.0+build.1734-mc1.20.1
# Get the correct version @ https://maven.createmod.net/dev/engine-room/flywheel/flywheel-fabric-1.20.1/
flywheel_fabric_version = 1.0.6-beta-269
# Get the correct version @ https://maven.createmod.net/net/createmod/ponder/Ponder-Fabric-1.20.1/
ponder_fabric_version = 1.0.92
# Get the correct version @ https://mvn.devos.one/#/snapshots/com/tterrag/registrate_fabric/Registrate
registrate_fabric_version = 1.3.79-MC1.20.1

#      ┌──────────────────────────────────────────────────────────┐
#      │                          FORGE                           │
#      └──────────────────────────────────────────────────────────┘
forge_version = 1.20.1-47.4.10
forge_version_range = [40,)
loader_version_range = [40,)

# ──────────────────────────────────── DEPENDENCIES ────────────────────────────────────
# Get the correct version @ https://maven.createmod.net/com/simibubi/create/
create_version = 6.0.8-290
# Get the correct version @ https://maven.createmod.net/dev/engine-room/flywheel/
flywheel_version = 1.0.6-beta-269
# Get the correct version @ https://maven.createmod.net/net/createmod/ponder/
ponder_version = 1.0.92
# Get the correct version @ https://maven.tterrag.com/com/tterrag/registrate/Registrate/
registrate_version = MC1.20-1.3.3
