name: Module Enhancement
description: Supported Mod missing a block or an item via new version? 
title: "[🗃]: "
labels: ["Module-Enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Module Enhancement

  - type: dropdown
    id: version-loader
    attributes:
      label: Version - Loader
      description: "What's the Minecraft version & loader"
      options:
        - Unknown
        - 1.21.1 - FABRIC
        - 1.20.1 - FABRIC
        - 1.19.2 - FABRIC
        - 1.21.1 - NEOFORGE
        - 1.20.1 - FORGE
        - 1.19.2 - FORGE
        - 1.18.2
      default: 0
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Supported Mod Version
      description: "Current Version of the supported mod that adds new block/item"
      placeholder: ex. v2.2.0
    validations:
      required: true

  - type: input
    id: curseforge
    attributes:
      label: "Supported mod's Curseforge"
      description: "The link for supported mod's Curseforge"
      placeholder: ex. https://www.curseforge.com/minecraft/mc-mods/macaws-windows
    validations:
      required: true

  - type: textarea
    attributes:
      label: Details
      description: |
        List the missing block/items that have been recently added and is not supported in the module via Every Compat
      placeholder: "ex: Macaw's Windows v2.2.0 has added 3 new blocks:\n- <TYPE> Pane Window\n- Stripped <TYPE> Pane Window\n- <TYPE> Plank Pane Window"
    validations:
      required: true
