plugins {
    id "com.github.johnrengelman.shadow" version "7.1.2"
}

architectury {
    platformSetupLoomIde()
    forge()
}


loom {
    accessWidenerPath = project(":common").loom.accessWidenerPath

    forge {
        convertAccessWideners = true
        extraAccessWideners.add loom.accessWidenerPath.get().asFile.name

        mixinConfig  "everycomp-common.mixins.json"

    }
}

configurations {
    common
    shadowCommon // Don't use shadow from the shadow plugin because we don't want IDEA to index this.
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentForge.extendsFrom common
}


processResources {
    inputs.property "version", project.version
    //inputs.property "mod_name": project.getArchivesBaseName()

    filesMatching("META-INF/mods.toml") {
        expand "version": project.version
        expand "mod_name": project.getArchivesBaseName()
    }
}

shadowJar {
    exclude "fabric.mod.json"
    exclude "architectury.common.json"

    configurations = [project.configurations.shadowCommon]
    archiveClassifier = "dev-shadow"
}

remapJar {
    input.set shadowJar.archiveFile
    dependsOn shadowJar
    archiveClassifier = "forge"
}

remapSourcesJar {
    archiveClassifier = "forge-sources"
}

jar {
    archiveClassifier = "dev"
}

sourcesJar {
    def commonSources = project(":common").sourcesJar
    dependsOn commonSources
    from commonSources.archiveFile.map { zipTree(it) }

    archiveClassifier = "forge-sources"
}

components.java {
    withVariantsFromConfiguration(project.configurations.shadowRuntimeElements) {
        skip()
    }
}

publishing {
    publications {
        mavenForge(MavenPublication) {
            artifactId = rootProject.mod_id + "-" + project.name
            from components.java
        }
    }

    // See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
    repositories {
        // Add repositories to publish to here.
        maven {
            url = "https://www.cursemaven.com"
            allowInsecureProtocol = true
        }
    }
}

dependencies {
    forge "net.minecraftforge:forge:${forge_version}"

    common(project(path: ":common", configuration: "namedElements")) { transitive false }
    shadowCommon(project(path: ":common", configuration: "transformProductionForge")) { transitive = false }

    implementation 'org.jetbrains:annotations:22.0.0'

    implementation(annotationProcessor("io.github.llamalad7:mixinextras-common:${mixin_extras_version}"))
    implementation(include("io.github.llamalad7:mixinextras-forge:${mixin_extras_version}"))
    annotationProcessor 'net.fabricmc:sponge-mixin:0.12.5+mixin.0.8.5'

//!! MOONLIGHT LIB (REQUIRED) --------------------------------------------------------------------------------------- \\
    String path = System.getenv('REPOS20_1')
    boolean usesMavenLocalML =  System.getenv().MY_PC == "1"
    print "isMyPc (FORGE): $usesMavenLocalML\n"

        //- Repository LOCAL
    if (enable_moonlight_test.toBoolean()) {
        if (usesMavenLocalML) {
            //- ~/forge/mods LOCAL
            modImplementation("net.mehvahdjukaar:moonlight-forge:${project.moonlight_testVersion}") // LOCAL
        } else {
            modImplementation(files(path + "\\Moonlight\\forge\\build\\libs\\moonlight-${moonlight_testVersion}-forge.jar"))
        }
    } else {
        //+ MAVEN
        modImplementation("maven.modrinth:moonlight:${moonlight_mavenVersion}-forge") // v2.16.13
    }

//!! TOOLS ========================================================================================================== \\
    modRuntimeOnly("dev.emi:emi-forge:${emi_version}+${minecraft_version}")
    modRuntimeOnly("com.blamejared.crafttweaker:CraftTweaker-forge-${minecraft_version}:${crafttweaker_version}")
    modRuntimeOnly("curse.maven:jade-324717:6106101") // v11.12.3
    modRuntimeOnly("curse.maven:configured-457570:5180902") // v2.2.3
    modRuntimeOnly("curse.maven:jei-238222:6600311") // v15.20.0.112
//    modRuntimeOnly("curse.maven:worldedit-225608:4586218")

//!! ================================================ DEPENDENCIES ================================================== \\
    //- ONLY FOR TESTING - can be commented out or enabled
//    modRuntimeOnly("curse.maven:terrablender-563928:5378180") // v3.0.1.7 | BOP, Regions-Unexplored
//    modRuntimeOnly("curse.maven:glitchcore-955399:5787839") // v0.0.1.1 | BOP
    modRuntimeOnly("com.github.glitchfiend:TerraBlender-forge:${minecraft_version}-${terrablender_version}") // Biomes-O'-Plenty, Regions-Unexplored
    modRuntimeOnly("com.github.glitchfiend:GlitchCore-forge:${minecraft_version}-${glitchcore_version}") // Biomes-O'-Plenty
//    modRuntimeOnly("curse.maven:athena-841890:5176879") //
//    modRuntimeOnly("curse.maven:aeroblender-879879:4789008") // Aether
//    modRuntimeOnly("curse.maven:cloth-config-348521:4973441") // v11.1.118 | REI, Infinity-Buttons
//    modRuntimeOnly("curse.maven:architectury-api-419699:5137938") // v9.2.14 | REI, Furnish, Minecraft-Comes-Alive-Reborn, Garden-Of-The-Dead
//    modRuntimeOnly("curse.maven:resourceful-lib-570073:5659871")  // v2.1.29 | Handcrafted, Cozy, Ad-Astra
//    modRuntimeOnly("curse.maven:resourceful-config-714059:6231176")  // v2.1.3 | Ad-Astra
//    modRuntimeOnly("curse.maven:botarium-704113:5486070")  // v2.3.4 | Ad-Astra
//    modRuntimeOnly("curse.maven:flib-661261:5495793") // Absent-By-Design
//    modRuntimeOnly("curse.maven:supermartijn642s-core-lib-454372:5668859") // Rechiseled
//    modRuntimeOnly("curse.maven:supermartijn642s-config-lib-438332:4715408") // Rechiseled
//    modRuntimeOnly("curse.maven:rechiseled-558998:5286306") // Rechiseled @ ISN'T SUPPORTED YET
//    modRuntimeOnly("curse.maven:curios-309927:6418456") // v5.14.1 | Malum, Aether, Ars-Nouveau
//    modRuntimeOnly("curse.maven:lodestone-616457:5712854") // Malum
//    modRuntimeOnly("curse.maven:geckolib-388172:7025129") // v4.8.2 | Ars-Nouveau
    modRuntimeOnly("curse.maven:citadel-331936:6702068") // v2.6.2 | Alex's Cave, Rats
//    modRuntimeOnly("curse.maven:structure-gel-api-378802:5188368") // Blue-Skies
//    modRuntimeOnly("curse.maven:patchouli-306770:4636277") // v81 | TFC, Timber-Frames
//    modRuntimeOnly("curse.maven:monolib-968432:6123976") // v2.0.0 | More-Beautiful-Torches
//    modRuntimeOnly("curse.maven:brewin-and-chewin-637808:6237884") // Smidgeon-O'-Bliss
//    modRuntimeOnly("curse.maven:kotlin-for-forge-351264:5402061") // Adorn
//    modRuntimeOnly("curse.maven:ctm-267602:5983309") // Chipped

            //- OTHER MAVENS
//    modRuntimeOnly("maven.modrinth:fusion-connected-textures:1.2.7b-forge-mc${minecraft_version}") // Dawn-Of-Time, Timber-Frame, Rechiseled
//    modRuntimeOnly("maven.modrinth:midnightlib:1.4.2-forge") // Building-But-Better
//    forgeRuntimeLibrary("com.teamresourceful:bytecodecs:1.0.2") // Chipped, Ad-Astra
//    forgeRuntimeLibrary("com.teamresourceful:yabn:1.0.3") // Ad-Astra
//    modRuntimeOnly("dev.engine-room.flywheel:flywheel-forge-${minecraft_version}:${flywheel_version}") // Create
//    modRuntimeOnly("net.createmod.ponder:Ponder-Forge-${minecraft_version}:${ponder_version}") // Create

    //+ REQUIRED - The modules access libraries from below - ONLY IN FORGE
    modCompileOnly("curse.maven:autoreglib-250363:3857246")
    modCompileOnly("curse.maven:blueprint-382216:5292242") // v7.10 | The-Outer-End, +Woodworks, Boatload, Sully Mod
    modCompileOnly("curse.maven:valhelsia-core-416935:5189548") // v1.1.2 | Valhelsia Structure, Valhelsia Furniture
    modCompileOnly("curse.maven:framework-549225:5911986") // v0.7.12 | Refurbished Furniture, +Mighty-Mail, Backpacked
    modCompileOnly("curse.maven:quad-932715:5340148") // More Chest Variants, More Crafting Table
    modCompileOnly("curse.maven:titanium-287342:5468426") // v3.8.32 | Functional-Storage
    modCompileOnly("curse.maven:zeta-968868:6312779") // v1.0-28 | Quark

            // OTHER MAVENS
    modCompileOnly("com.tterrag.registrate:Registrate:${registrate_version}") // Create, The-Twilight-Forest, Tropicraft

//!! ================================================== IMPORTS ===================================================== \\
    //- ONLY FOR TESTING - can be commented out or enabled
//    modRuntimeOnly("curse.maven:another-furniture-610492:4034009") //WARNING: v2.1.2-1.19.2 -> 1.20.1: Cannot remap access widener from namespace 'srg'. Expected: 'intermediary'
//    modRuntimeOnly("curse.maven:backpacked-352835:5401965")
//    modRuntimeOnly("curse.maven:camp-chair-531744:4579679")
//    modCompileOnly("curse.maven:dawn-of-time-312359:6863591") // Fusion, YetAnotherConfigLib - NOTE: Test in production (PrismLauncher or others)
//    modRuntimeOnly("curse.maven:decorative-blocks-362528:5089406")
//    modRuntimeOnly("curse.maven:exlines-bark-carpets-527296:4094399")
//    modRuntimeOnly("curse.maven:farmersdelight-398521:6597298") // Smidgeon-O'-Bliss, Youkais-Homecoming
//    modRuntimeOnly("curse.maven:furnish-547069:4821511")
//    modRuntimeOnly("curse.maven:handcrafted-538214:5118729") // Resourceful-Lib
//    modRuntimeOnly("curse.maven:friends-and-foes-forge-602059:6354624")
//    modRuntimeOnly("curse.maven:missing-wilds-forge-634277:5053677")
//    modRuntimeOnly("curse.maven:more-beautiful-torches-860325:5263631") // Monolib
//    modRuntimeOnly("curse.maven:more-chest-variants-lieonlion-858032:5476605") // Quad - LieOnLion
//    modRuntimeOnly("curse.maven:more-crafting-tables-lieonlion-913586:5330971") // Quad - LieOnLion
//    modRuntimeOnly("curse.maven:refurbished-furniture-897116:6272885") // Framework
//    modRuntimeOnly("curse.maven:storage-drawers-223852:6994481")
//    modRuntimeOnly("curse.maven:valhelsia-furniture-694349:5189602") // Valhelsia-Core
//    modRuntimeOnly("curse.maven:table-top-craft-467136:5318681")
//    modRuntimeOnly("curse.maven:twigs-496913:4605097")
//    modRuntimeOnly("curse.maven:variant-vanilla-blocks-866509:4997060") //v1.3.6
//    modRuntimeOnly("curse.maven:villagersplus-forge-817272:4996995")

            //- OTHER MAVENS
//    modRuntimeOnly("maven.modrinth:stylish-stiles:l9FFA4BK")
//    modRuntimeOnly("fuzs.diagonalblocks:diagonalblocks-forge:8.0.6")
//    modRuntimeOnly("earth.terrarium.chipped:chipped-forge-${minecraft_version}:3.0.7") //INCLUDED: Athena, Resourceful-Lib, REQUIRED: Bytecodecs, ConnectedTexturesMod (CTM)

            //- ~/forge/mods LOCAL
//    modRuntimeOnly("com.arcanc.bc:beautifulcampfires-forge-1.20.1-1.0.1")


    //+ REQUIRED - The modules access libraries from below - ONLY IN FORGE
        // ~/forge/mods LOCAL
    modCompileOnly("net.stehschnitzel.shutter:shutters-2.0.2-1.20.1")
    modCompileOnly("com.tynoxs.buildersdelight:BuildersDelight-1.20.1-v.1.3")
    modCompileOnly("blocks_plus:blocks+1.20.1-1.7")

        // MACAW's
    modCompileOnly("curse.maven:macaws-bridges-351725:5240518")
    modCompileOnly("curse.maven:macaws-doors-378646:4649910")
    modCompileOnly("curse.maven:macaws-fences-and-walls-453925:6363155")
    modCompileOnly("curse.maven:macaws-furniture-359540:4726300")
    modCompileOnly("curse.maven:macaws-lights-and-lamps-502372:5450327")
    modCompileOnly("curse.maven:macaws-paths-and-pavings-629153:5054882")
    modCompileOnly("curse.maven:macaws-roofs-352039:4590032")
    modCompileOnly("curse.maven:macaws-trapdoors-400933:4841553")
    modCompileOnly("curse.maven:macaws-windows-363569:4961142")
    modCompileOnly("curse.maven:macaws-stairs-1119394:6155181")

        // GENERAL
    modCompileOnly("curse.maven:absent-by-design-305840:4616702")
    modCompileOnly("curse.maven:architects-palette-433862:5036133")
    modCompileOnly("curse.maven:beautify-decorate-633252:4781709")
    modCompileOnly("curse.maven:boatload-337396:5292325") // Blueprint
    modCompileOnly("curse.maven:buildersaddition-389697:4660499")
    modCompileOnly("curse.maven:corail-pillar-266228:5073954")
    modCompileOnly("curse.maven:decoration-delight-687475:5563942")
    modCompileOnly("curse.maven:domum-ornamentum-527361:4174257")
    modCompileOnly("curse.maven:dramatic-doors-380617:6438745")
    modCompileOnly("curse.maven:excessive-building-845097:5442075")
    modCompileOnly("curse.maven:functional-storage-556861:5373105") // Titanium
    modCompileOnly("curse.maven:infinity-buttons-661902:5330420") // Cloth-Config
    modCompileOnly("curse.maven:just-a-raft-mod-274350:5777239")
    modCompileOnly("curse.maven:lightmans-currency-472521:6524190")
    modCompileOnly("curse.maven:mighty-mail-902986:4750272")
    modCompileOnly("curse.maven:more-crafting-tables-for-forge-417365:4786212")
    modCompileOnly("curse.maven:mosaic-carpentry-690226:4068673")
    modCompileOnly("curse.maven:mrcrayfish-furniture-mod-55438:4602980")
    modCompileOnly("curse.maven:nosiphus-furniture-mod-593876:6169762") // MrCrayFish's-Furniture-Mod-(LEGACY)
    modCompileOnly("curse.maven:oreberries-replanted-454062:5138729")
    modCompileOnly("curse.maven:pokecube-aoi-285121:4816899")
    modCompileOnly("curse.maven:premium-wood-353515:3905203")
    modCompileOnly("curse.maven:productivebees-377897:5566102") //v12.6.0 | WIP
    modCompileOnly("curse.maven:quark-243121:6312787") // Zeta - IMPORTANT: modRuntimeOnly mustn't be set blc it causes issue in production
    modCompileOnly("curse.maven:redeco-897377:5603009")
    modCompileOnly("curse.maven:regions-unexplored-659110:5558225")
    modCompileOnly("curse.maven:smidgeon-o-bliss-remastered-1288021:6710528") // Farmer's-Delight, Brewing'-And-Chewin' - NOTE: Test in production (PrismLauncher or others), idk why it don't work in DEV
    modCompileOnly("curse.maven:storage-delight-forge-979761:6696771")
    modCompileOnly("curse.maven:the-graveyard-forge-531188:4025847")
    modCompileOnly("curse.maven:the-twilight-forest-227639:5468648")
    modCompileOnly("curse.maven:timber-frames-606011:5372390")
    modCompileOnly("curse.maven:tropicraft-254794:4811116") // Registrate
    modCompileOnly("curse.maven:ultimate-car-mod-267458:5982592")
    modCompileOnly("curse.maven:unusual-furniture-1278034:6604940")
    modCompileOnly("curse.maven:valhelsia-structures-347488:5195707") // Valhelsia-Core
    modCompileOnly("curse.maven:variant-crafting-tables-565095:4585921")
    modCompileOnly("curse.maven:woodster-869951:4670471")
    modCompileOnly("curse.maven:woodworks-543610:5228779") // Blueprint
    modCompileOnly("curse.maven:workshop-for-handsome-adventurer-875843:5713529")
    modCompileOnly("curse.maven:xercamod-341575:4667995")
    modCompileOnly("curse.maven:youkais-homecoming-957437:6724147") // Farmer's-Delight - Use Production instead of modImplementation

            // OTHER MAVENS
    modCompileOnly("maven.modrinth:building-but-better:1.20.1-1.1.1") // MidnightLib
    modCompileOnly("com.simibubi.create:create-${minecraft_version}:${create_version}:slim") { transitive = false } // Registrate, Flywheel, Ponder

    //- ======================================= DISABLED FOR A REASON =============================================== \\
//    modCompileOnly("curse.maven:alekiships-1068445:5963449") //!! NOT STARTED
    //modCompileOnly("com.polipo.bookshelf:giacomos_bookshelf-1.20.1-1.3.9") // WIP
//    modImplementation("tech.thatgravyboat.cozy:cozy-1.1.1-forge") //Failed to process jar when running jar processor: fabric-loom:access-widener
    // implementation fg.deobf("curse.maven:marg-324494:3723497") // LIBRARY
    // implementation fg.deobf("curse.maven:ortuslib-616457:3768197") // LIBRARY
    // implementation fg.deobf("curse.maven:project-brazier-238326:3835038")

    // modImplementation("curse.maven:benched-417063:3821546") // Use OBJ Format

//     modRuntimeOnly("curse.maven:malum-484064:5718038") // MAGIC MOD & use BBModel

//!! ============================================== FOR TESTING ===================================================== \\

//    modRuntimeOnly("curse.maven:framedblocks-441647:6685443")
//    forgeRuntimeLibrary("com.github.ben-manes.caffeine:caffeine:3.2.1")

//    modRuntimeOnly("curse.maven:endless-biomes-667688:5109705")
//    modRuntimeOnly("curse.maven:blue-skies-312918:5010316") // structure-gel-api
//    modRuntimeOnly("curse.maven:biomes-o-plenty-220318:6364065") // Terrablender, Glitchcore
//    modRuntimeOnly("curse.maven:productivetrees-867074:5486574") // Terrablender, Glitchcore, ProductiveLib
    modRuntimeOnly("curse.maven:alexs-caves-924854:5848216") // Citadel
//    modRuntimeOnly("curse.maven:gardens-of-the-dead-683174:4784269") // Architectury-API
//    modRuntimeOnly("curse.maven:rats-323596:5904296")
//    modRuntimeOnly("curse.maven:mo-shiz-mod-62536:5587177")
//    modRuntimeOnly("curse.maven:aether-255308:5889509") // Curios
//    modRuntimeOnly("curse.maven:ancient-aether-886751:6013933") // Aether
//    modRuntimeOnly("curse.maven:pfw-aesthetic-gems-906404:6023817")
//    modRuntimeOnly("curse.maven:deeperdarker-659011:5906086")
//    modRuntimeOnly("curse.maven:gregtechceu-modern-890405:6862094")
//    modRuntimeOnly("curse.maven:sullys-mod-386534:6005769") // Blueprint
//    modRuntimeOnly("curse.maven:upgrade-aquatic-326895:5296565") // Blueprint
//    modRuntimeOnly("curse.maven:autumnity-365045:5292346") // Blueprint
//    modRuntimeOnly("curse.maven:the-outer-end-430404:5812948") // Blueprint
//    modRuntimeOnly("curse.maven:caverns-and-chasms-438005:6040957") // Blueprint
//    modRuntimeOnly("curse.maven:atmospheric-362393:6393127") // Blueprint
//    modRuntimeOnly("curse.maven:environmental-388992:6060255") // Blueprint
//    modRuntimeOnly("curse.maven:ad-astra-635042:6262032") // Botarium, Resourceful-Config, Resourceful-Lib, Bytecodecs
//    modRuntimeOnly("curse.maven:soulful-nether-1146098:6376431") // Elysium-API
//    modRuntimeOnly("curse.maven:elysium-api-1158628:6376984") // Soulful-Nether

//    modRuntimeOnly("curse.maven:terrafirmacraft-302973:6739107") // patchouli

    //!! OTHERS
//    modRuntimeOnly("maven.modrinth:stone-zone:1.20-2.7.14") //REQUIRE: Stone Mods

}
