{
  "formatVersion": "1.1",
  "component": {
    "group": "net.mehvahdjukaar",
    "module": "moonlight",
    "version": "1.19.2-2.1.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "moonlight-1.19.2-2.1.20.jar",
          "url": "moonlight-1.19.2-2.1.20.jar",
          "size": 591289,
          "sha512": "473e30a3f1a630b7111ac9c5bc7a45abfc7e67ae759427751797c526e25c1f24718f18092119c478e96f925c62af153b545f152bc6bd3304b12be87ec22a59f9",
          "sha256": "cb0cd5334e5c26681f06690a77d67159e3f130fb9fc3601ed11e8caeffd7b9dd",
          "sha1": "0d3f218b5c780b56da7d1eb38ed233340ae6f6d5",
          "md5": "0f85731e23cee99f110b32e79b239df5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.9"
          }
        }
      ],
      "files": [
        {
          "name": "moonlight-1.19.2-2.1.20.jar",
          "url": "moonlight-1.19.2-2.1.20.jar",
          "size": 591289,
          "sha512": "473e30a3f1a630b7111ac9c5bc7a45abfc7e67ae759427751797c526e25c1f24718f18092119c478e96f925c62af153b545f152bc6bd3304b12be87ec22a59f9",
          "sha256": "cb0cd5334e5c26681f06690a77d67159e3f130fb9fc3601ed11e8caeffd7b9dd",
          "sha1": "0d3f218b5c780b56da7d1eb38ed233340ae6f6d5",
          "md5": "0f85731e23cee99f110b32e79b239df5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "moonlight-1.19.2-2.1.20-sources.jar",
          "url": "moonlight-1.19.2-2.1.20-sources.jar",
          "size": 340803,
          "sha512": "e1849769778c7e15e1d21dae466e2ba8c30751fae224093ecb100090b8e3a3a2d374178281065e0691b93710c4de30fd7fa5990d1a0e6a3adcadd3afeccc2e33",
          "sha256": "2630e7a2875533401107c9c13336a531cd9a028687b3c41e6a0a4e81d87bde23",
          "sha1": "0696a578ec1d4216ca89da959ef966fa14ac0a77",
          "md5": "c1ea18c653ed58a57fe0336c44a66ad0"
        }
      ]
    }
  ]
}
