{
  "formatVersion": "1.1",
  "component": {
    "group": "net.mehvahdjukaar",
    "module": "moonlight",
    "version": "1.19.2-2.0.37",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "moonlight-1.19.2-2.0.37.jar",
          "url": "moonlight-1.19.2-2.0.37.jar",
          "size": 563027,
          "sha512": "cee6628543b5dbcbbf88715a075f5c80d0cceec1c86aec57f105c30f5b02a5e397596e73d5a7b7cb5f952451b9bb05ddc0b0850708f7f6592906893f55d494b7",
          "sha256": "6f70dca74e87d63ac6c16fba0dac4ef56784483836f4ea1fd91975be27407a1d",
          "sha1": "44225d17420ca32a47c9afe949eb6f33d9af49e4",
          "md5": "61c32d49df25498409452ec85f80dae1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.9"
          }
        }
      ],
      "files": [
        {
          "name": "moonlight-1.19.2-2.0.37.jar",
          "url": "moonlight-1.19.2-2.0.37.jar",
          "size": 563027,
          "sha512": "cee6628543b5dbcbbf88715a075f5c80d0cceec1c86aec57f105c30f5b02a5e397596e73d5a7b7cb5f952451b9bb05ddc0b0850708f7f6592906893f55d494b7",
          "sha256": "6f70dca74e87d63ac6c16fba0dac4ef56784483836f4ea1fd91975be27407a1d",
          "sha1": "44225d17420ca32a47c9afe949eb6f33d9af49e4",
          "md5": "61c32d49df25498409452ec85f80dae1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "moonlight-1.19.2-2.0.37-sources.jar",
          "url": "moonlight-1.19.2-2.0.37-sources.jar",
          "size": 327715,
          "sha512": "6f3fba429feae8d3b85016a8ead00f9d9c5d6197d0ba5848c2bed874055598a0010b1291312c0ffdba90d9205ea631eedf4f7f981842f4e5767f179f97446fbf",
          "sha256": "94c1a5f70143e91ea94953b6867ffd60389e4008e8c0d2ca179abec3c7891db8",
          "sha1": "ae3bec9795a0aa2163bba62328e6015833676249",
          "md5": "953d42fa7721d69d5db036d3f307e65e"
        }
      ]
    }
  ]
}
