architectury {
    common(rootProject.enabled_platforms.split(","))
}

loom {
    accessWidenerPath = file("src/main/resources/everycomp.accesswidener")
}

dependencies {
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modApi "net.fabricmc.fabric-api:fabric-api:${rootProject.fabric_api_version}"


    annotationProcessor 'net.fabricmc:sponge-mixin:0.12.5+mixin.0.8.5'

    //common. Fabric version that works on both
    modCompileOnly("curse.maven:resourceful-lib-570073:5659872") // v2.1.29
    modCompileOnly("curse.maven:architectury-api-419699:5137936") // v9.2.14

//!! MOONLIGHT LIB (REQUIRED) --------------------------------------------------------------------------------------- \\
    String path = System.getenv('REPOS20_1')

    //- LOCAL
    if (enable_moonlight_test.toBoolean()) {
        modImplementation(files(path + "\\Moonlight\\forge\\build\\libs\\moonlight-${moonlight_testVersion}-forge.jar"))
    }
    //+ MAVEN
    else {
        modApi("net.mehvahdjukaar:moonlight:${moonlight_mavenVersion}"){
            transitive = false
        }
    }


//!! ============================================ DEPENDENCIES ====================================================== \\
    //+ REQUIRED - The modules access libaries from below
    modCompileOnly("curse.maven:framework-549225:5911975") // v0.7.12 | Furniture Refurbished
    modCompileOnly("curse.maven:valhelsia-core-416935:5376599") // Valhelsia-Furniture
    modCompileOnly("curse.maven:zeta-968868:5078215") // v1.0-13 | Quark

        //+ OTHER MAVENS

        //+ ~/common/mods LOCAL
//    modCompileOnly("net.stehschnitzel.shutter:shutter-2.0.2-1.20.1")

//!! ================================================== IMPORTS ===================================================== \\
    //+ REQUIRED - The modules access libaries from below

    // MACAW's
    modCompileOnly("curse.maven:macaws-bridges-351725:5240495") // ABSTRACT not created yet
    modCompileOnly("curse.maven:macaws-doors-378646:4649888") // ABSTRACT not created yet
    modCompileOnly("curse.maven:macaws-fences-and-walls-453925:6363061") // ABSTRACT not created yet
    modCompileOnly("curse.maven:macaws-lights-and-lamps-502372:5450302") // ABSTRACT not created yet
    modCompileOnly("curse.maven:macaws-paths-and-pavings-629153:5054857") // ABSTRACT not created yet
    modCompileOnly("curse.maven:macaws-roofs-352039:4590013") // ABSTRACT not created yet
    modCompileOnly("curse.maven:macaws-trapdoors-400933:4841534") // ABSTRACT not created yet
    modCompileOnly("curse.maven:macaws-windows-363569:4750644") // ABSTRACT not created yet
    modCompileOnly("curse.maven:macaws-furniture-359540:7197865")
    modCompileOnly("curse.maven:macaws-stairs-1119394:6155218") // ABSTRACT not created yet

    //+ GENERAL
    modCompileOnly("curse.maven:another-furniture-610492:4815126")
    modCompileOnly("curse.maven:backpacked-352835:5401968")
    modCompileOnly("curse.maven:beautiful-campfires-1085950:6162183")
    modCompileOnly("curse.maven:blockus-312289:6256096")
    modCompileOnly("curse.maven:building-but-better-989479:6803573")
    modCompileOnly("curse.maven:camp-chair-531744:4579679")
    modCompileOnly("curse.maven:chipped-456956:4634858") // v3.0.1
    modCompileOnly("curse.maven:create-fabric-624165:5982726")
    modCompileOnly("curse.maven:dawn-of-time-312359:6863594")
    modCompileOnly("curse.maven:decorative-blocks-362528:5089408")
    modCompileOnly("curse.maven:exlines-bark-carpets-527296:4661550")
    modCompileOnly("curse.maven:farmers-delight-refabricated-993166:6626608")
    modCompileOnly("curse.maven:friends-and-foes-551364:6354623")
    modCompileOnly("curse.maven:furnish-547069:4821511")
    modCompileOnly("curse.maven:handcrafted-538214:5118730")
    modCompileOnly("curse.maven:hearth-and-home-849364:4828281")
//    modCompileOnly("curse.maven:more-beautiful-torches-860325:5263631") // MonoLib - Not really needed
    modCompileOnly("curse.maven:more-chest-variants-lieonlion-858032:5476602") // Quad - LieOnLion
    modCompileOnly("curse.maven:more-crafting-tables-lieonlion-913586:5330969") // Quad - LieOnLion
    modCompileOnly("curse.maven:refurbished-furniture-897116:6272883") // Framework
    modCompileOnly("curse.maven:quark-243121:5093415")
    modCompileOnly("curse.maven:storage-drawers-223852:6994478")
    modCompileOnly("curse.maven:table-top-craft-fabric-729535:5319819")
    modCompileOnly("curse.maven:twigs-496913:4605097")
    modCompileOnly("curse.maven:variant-vanilla-blocks-866509:5150741") //v1.3.8
    modCompileOnly("curse.maven:valhelsia-furniture-694349:5189603")
    modCompileOnly("curse.maven:villagersplus-fabric-809542:4996993")
    modCompileOnly("curse.maven:missing-wilds-622590:5053651")

    //+ OTHER MAVENs
    modCompileOnly("maven.modrinth:stylish-stiles:zLlRqz68")

//!! ========================================== DISABLED FOR A REASON =============================================== \\

//    modCompileOnly("curse.maven:the-twilight-forest-227639:4653704") //!! NOT AVAILABLE
//    modCompileOnly("curse.maven:missing-wilds-622590:3891602")

}

publishing {
    publications {
        mavenCommon(MavenPublication) {
            artifactId = rootProject.mod_id
            from components.java
        }
    }

    repositories {
        // Add repositories to publish to here.
    }
}
