
modLoader = "javafml"
loaderVersion = "${loader_version_range}"

license = "${mod_license}"
issueTrackerURL = "${mod_github}/issues"


[[mixins]]
config = "${mod_id}-common.mixins.json"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
logoFile = "icon.png"
authors = "${mod_authors}"
credits = "${mod_credits}"
description = '''${mod_description}'''
modUrl = "${mod_homepage}"
itemIcon = "everycomp:all_woods" #catalogue icon

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_min_version},${minecraft_max_version})"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${mod_id}]]
modId = "moonlight"
type = "required"
referralUrl = "https://www.curseforge.com/minecraft/mc-mods/selene"
versionRange = "[1.21-2.23.2,]"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "create"
type = "optional"
referralUrl = "https://www.curseforge.com/minecraft/mc-mods/create"
versionRange = "[1.21.1-6.0.2,]"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "woodster"
type = "optional"
referralUrl = "https://www.curseforge.com/minecraft/mc-mods/woodster"
versionRange = "[2.0.1,]"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "mcwdoors"
type = "optional"
referralUrl = "https://www.curseforge.com/minecraft/mc-mods/macaws-doors"
versionRange = "[1.1.2,]"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "mcwtrpdoors"
type = "optional"
referralUrl = "https://www.curseforge.com/minecraft/mc-mods/macaws-trapdoors"
versionRange = "[1.1.4,]"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "blockus"
type = "optional"
referralUrl = "https://www.curseforge.com/minecraft/mc-mods/blockus"
versionRange = "[2.9.11,]"
ordering = "AFTER"
side = "BOTH"
